[package]
name = "polkadot-erasure-coding"
version = "0.8.22"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
primitives = { package = "polkadot-primitives", path = "../primitives" }
reed_solomon = { package = "reed-solomon-erasure", version = "4.0.2"}
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/KILTprotocol/substrate", rev = "68014e8a0" }
trie = { package = "sp-trie", git = "https://github.com/KILTprotocol/substrate", rev = "68014e8a0" }
derive_more = "0.15.0"
